version: '3.8'

services:
  app:
    build: .
    container_name: app-isbn-to-markdown-api
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${DOMAIN_NAME:-isbn-scanner.local}`)"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.routers.app.tls=true"
    networks:
      - web

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
    ports:
      - "3200:80"
      - "3201:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/certs:/etc/certs:ro"
      - "./traefik/dynamic:/etc/traefik/dynamic:ro"
    networks:
      - web

networks:
  web:
    name: isbn-scanner-network
